module.exports = {
    "Ahafo Region": {
        "Asunafo North": { code: "HA", cities: ["Goaso", "Mim", "Akrodie", "Fawohoyeden", "Ayomso", "Dominase", "Bediako", "Kasapin", "Pomaakrom", "Kenyasi"] },
        "Asunafo South": { code: "HB", cities: ["Kukuom", "Sankore", "Noberkaw", "Abuom", "Dantano", "Anwiam", "Naketete", "Kwapong"] },
        "Asutifi North": { code: "HQ", cities: ["Kenyasi No. 1", "Kenyasi No. 2", "Ntotroso", "Gambia No. 2", "Gyedu", "Wamahinso", "Ola Resettlement"] },
        "Asutifi South": { code: "HR", cities: ["Hwidiem", "Acherensua", "Dadiesoaba", "Nkrankrom", "Sienchem", "Nkaseim"] },
        "Tano North": { code: "HT", cities: ["Duayaw Nkwanta", "Yamfo", "Bomaa", "Terchire", "Adrobaa", "Susuanso", "Tanoso"] },
        "Tano South": { code: "HS", cities: ["Bechem", "Techimantia", "Derma", "Dwomo", "Brosankro", "Old Brosankro"] }
    },
    "Ashanti Region": {
        "Adansi North": { code: "A2", cities: ["Fomena", "Dompoase", "Medoma", "Patakro", "Kwapia", "Akrokerri", "Kusa"] },
        "Adansi South": { code: "A3", cities: ["New Edubiase", "Atobiase", "Wuruyie", "Akrofuom", "Tonkoase"] },
        "Adansi Asokwa": { code: "A5", cities: ["Adansi Asokwa", "Bodwesango", "Ffumso", "Anhwiaso"] },
        "Afigya Kwabre": { code: "AF", cities: ["Kodie", "Atimatim", "Afrancho", "Bronkong", "Buoho", "Eshiem", "Mpobi"] },
        "Afigya Kwabre North": { code: "AAK", cities: ["Boamang", "Ahenkro", "Tetrem", "Kyekyewire", "Maase"] },
        "Ahafo Ano North": { code: "AX", cities: ["Tepa", "Manfo", "Subriso", "Mabang", "Anyinasuso", "Betinko", "Akrofoso"] },
        "Ahafo Ano South East": { code: "A8", cities: ["Dwinyame", "Adugyama", "PokuKrom", "Barniekrom"] },
        "Ahafo Ano South West": { code: "AY", cities: ["Mankranso", "Kunsu", "Wioso", "Potrikrom"] },
        "Akrofuom": { code: "AAF", cities: ["Akrofuom", "Ampunyase", "Grumesa", "Sikaman"] },
        "Amansie Central": { code: "AV", cities: ["Jacobu", "Tweapease", "Fiankoma", "Numereso"] },
        "Amansie South": { code: "AAM", cities: ["Manso Adubia", "Datano", "Tontokrom", "Keniago"] },
        "Amansie West": { code: "AW", cities: ["Manso Nkwanta", "Pakyi No. 1", "Pakyi No. 2", "Antoakrom", "Abore", "Agroyesum", "Manso Atwere"] },
        "Asante Akim Central": { code: "AC", cities: ["Konongo", "Odumase", "Dwease", "Praaso", "Onyemso"] },
        "Asante Akim North": { code: "AN", cities: ["Agogo", "Hwidiem", "Juansa", "Amantenaman"] },
        "Asante Akim South": { code: "AA", cities: ["Juaso", "Obogu", "Bompata", "Asankare", "Ofoase", "Banka", "Kumeso"] },
        "Asokore Mampong": { code: "AS", cities: ["Sawaba", "Aboabo", "Asokore Mampong"] },
        "Asokwa": { code: "AAS", cities: ["Asokwa", "Atonsu", "Chirapatre", "Kaase"] },
        "Atwima Kwanwoma": { code: "AG", cities: ["Twedie", "Trede", "Bamenase", "Foase", "Trabuom"] },
        "Atwima Mponua": { code: "AI", cities: ["Nyinahin", "Mpasatia", "Tanodumase", "Kwanfinfi"] },
        "Atwima Nwabiagya": { code: "AH", cities: ["Nkawie", "Abuakwa", "Toase", "Asuofua", "Sepaase", "Bareese"] },
        "Atwima Nwabiagya North": { code: "AAT", cities: ["Barekese", "Fufuo", "Adankwame", "Marban"] },
        "Bekwai": { code: "AB", cities: ["Bekwai", "Kokofu", "Essumeja", "Anwiankwanta", "Dominase", "Poano"] },
        "Bosome Freho": { code: "A4", cities: ["Asiwa", "Tebeso", "Nsuaem", "Danyase"] },
        "Bosomtwe": { code: "AT", cities: ["Kuntanase", "Jachie", "Pramso", "Esaase", "Abono"] },
        "Ejisu": { code: "AE", cities: ["Ejisu", "Famesua", "Onwe", "Kwaso", "Bonwire", "Tikrom", "Donyina"] },
        "Ejura-Sekyedumase": { code: "AJ", cities: ["Ejura", "Sekyedumase", "Anyinasu", "Hiawoanwu"] },
        "Juaben": { code: "AL", cities: ["Juaben", "Boamadumasi"] },
        "Kumasi": { code: "AK", cities: ["Kumasi", "Adum", "Bantama", "Nhyiaeso", "Subin", "Dichemso", "Asafo", "Manhyia"] },
        "Kwadaso": { code: "AKW", cities: ["Kwadaso", "Tanoso", "Nwamase"] },
        "Kwabre East": { code: "AD", cities: ["Mamponteng", "Ahwiaa", "Ntonso", "Bonwire", "Fawoade", "Asonomaso", "Sakora Wonoo", "Kenyasi"] },
        "Mampong": { code: "AM", cities: ["Mampong", "Kofiase", "Adidwan", "Yonso", "Benim"] },
        "Obuasi": { code: "AO", cities: ["Obuasi", "Wawasi", "Brahabebome", "Boete", "Kwabrafoso"] },
        "Obuasi East": { code: "AOE", cities: ["Tutuka", "Wawasi", "Bossman", "Boete"] },
        "Offinso North": { code: "A6", cities: ["Akomadan", "Nkenkaasu", "Afrancho", "Kobreso"] },
        "Offinso South": { code: "A7", cities: ["Offinso", "Abofour", "Namong", "Samproso", "Asuoso"] },
        "Oforikrom": { code: "AOK", cities: ["Oforikrom", "Ayeduase", "Kentinkrono", "Emena", "Bomso", "Anwomaso"] },
        "Old Tafo": { code: "AOT", cities: ["Tafo", "Pankrono"] },
        "Sekyere Afram Plains": { code: "AP", cities: ["Drobonso", "Anyinofi"] },
        "Sekyere Central": { code: "AQ", cities: ["Nsuta", "Beposo", "Atonsu", "Kwamang"] },
        "Sekyere East": { code: "AR", cities: ["Effiduase", "Asokore", "Senchi"] },
        "Sekyere Kumawu": { code: "AU", cities: ["Kumawu", "Bodomase", "Woraso", "Besoro"] },
        "Sekyere South": { code: "AZ", cities: ["Agona", "Jamasi", "Wiamoase", "Banimu", "Kona"] },
        "Suame": { code: "ASU", cities: ["Suame", "Breman", "Kronum"] }
    },
    "Bono Region": {
        "Banda": { code: "BA", cities: ["Banda Ahenkro", "Bui", "Sabiye", "Bungase"] },
        "Berekum East": { code: "BB", cities: ["Berekum", "Kato", "Senase", "Biadan"] },
        "Berekum West": { code: "BC", cities: ["Jinijini", "Fetentaa", "Koraso", "Jamdede"] },
        "Dormaa Central": { code: "BD", cities: ["Dormaa Ahenkro", "Amachu", "Antwirifo", "Kyeremasu", "Babianeha"] },
        "Dormaa East": { code: "BE", cities: ["Wamfie", "Wamanafo", "Akontanim", "Kyeremasu"] },
        "Dormaa West": { code: "BF", cities: ["Nkrankwanta", "Kwameasua", "Diabaa"] },
        "Jaman North": { code: "BJ", cities: ["Sampa", "Sumaa Ahenkro", "Duadaso", "Jankufa"] },
        "Jaman South": { code: "BI", cities: ["Drobo", "Japekrom", "Dwenem", "Adamsu"] },
        "Sunyani": { code: "BS", cities: ["Sunyani", "Abesim", "New Dormaa", "Kotokrom", "Yawhima", "Ahyiayem"] },
        "Sunyani West": { code: "BY", cities: ["Odumase", "Fiapre", "Nsoatre", "Chiraa", "Dumasua", "Mantukwa"] },
        "Tain": { code: "BZ", cities: ["Nsawkaw", "Seikwa", "Badu", "Debibi", "Brodi"] },
        "Wenchi": { code: "BW", cities: ["Wenchi", "Amponsahkrom", "Subinso", "Tromeso"] }
    },
    "Bono East Region": {
        "Atebubu-Amantin": { code: "TA", cities: ["Atebubu", "Amantin", "Jato Zongo", "Akokoa"] },
        "Kintampo North": { code: "TK", cities: ["Kintampo", "Babile", "Gulumpe", "Kadelso", "Dawadawa", "Kawampe"] },
        "Kintampo South": { code: "TL", cities: ["Jema", "Amoma", "Anyima", "Apesika"] },
        "Nkoranza North": { code: "TN", cities: ["Busunya", "Yefri", "Dromankese", "Kranka"] },
        "Nkoranza South": { code: "TO", cities: ["Nkoranza", "Donkro Nkwanta", "Akumsa Domase", "Nkwabeng"] },
        "Pru East": { code: "TP", cities: ["Yeji", "Parambo", "Kobre", "Konkoma"] },
        "Pru West": { code: "TW", cities: ["Prang", "Abease", "Zabrama"] },
        "Sene East": { code: "TE", cities: ["Kajaji", "Bassa", "Nyankontre"] },
        "Sene West": { code: "TS", cities: ["Kwame Danso", "Kyeamekrom", "Lemu", "Bantama"] },
        "Techiman": { code: "TT", cities: ["Techiman", "Kenten", "Tanoso", "Forikrom", "Bamiri", "Tuobodom", "Sansama"] },
        "Techiman North": { code: "TX", cities: ["Tuobodom", "Offuman", "Aworowa", "Krobo"] }
    },
    "Central Region": {
        "Abura Asebu Kwamankese": { code: "CA", cities: ["Abura Dunkwa", "Abakrampa", "Asebu", "Moree", "Ayeldu", "Odonkorkrom", "Batanyaa"] },
        "Agona East": { code: "CP", cities: ["Nsaba", "Duakwa", "Kwanyako", "Mankrong", "Agona Asafo"] },
        "Agona West": { code: "CO", cities: ["Swedru", "Nyakrom", "Nkum", "Bobikuma", "Abodom"] },
        "Ajumako Enyan Esiam": { code: "CJ", cities: ["Ajumako", "Enyan Denkyira", "Bisease", "Breman Essiam", "Sonkwa", "Mando", "Ba"] },
        "Asikuma Odoben Brakwa": { code: "CB", cities: ["Breman Asikuma", "Odoben", "Brakwa", "Bedum", "Jamra", "Kwanan"] },
        "Assin Central": { code: "CN", cities: ["Assin Fosu", "Assin Dompim", "Juaso", "Assin Akropong"] },
        "Assin North": { code: "CR", cities: ["Assin Bereku", "Assin Praso", "Akonfudi", "Assin Kushea"] },
        "Assin South": { code: "CS", cities: ["Nsuaem Kyekyewere", "Assin Manso", "Nyankumasi", "Darmang", "Assin Jakai", "Andoe"] },
        "Awutu Senya East": { code: "CX", cities: ["Kasoa", "Opeikuma", "Iron City", "Nyanyano Kakraba", "Millennium City"] },
        "Awutu Senya West": { code: "CW", cities: ["Awutu Breku", "Bawjiase", "Senya Beraku", "Bontrase", "Obrakyere"] },
        "Cape Coast": { code: "CC", cities: ["Cape Coast", "UCC Campus", "Abura", "Pedu", "Ekon", "Adisadel", "Ola", "Kotokuraba", "Amamoma"] },
        "Effutu": { code: "CE", cities: ["Winneba", "Sankor", "Gyahadze", "Essuekyir"] },
        "Ekumfi": { code: "CF", cities: ["Essarkyir", "Otuam", "Eyisam", "Narkwa", "Ekrawfo", "Nanabin"] },
        "Gomoa Central": { code: "CL", cities: ["Afransi", "Obuasi", "Awombrew", "Ekwamkrom", "Gomoa Manso"] },
        "Gomoa East": { code: "CG", cities: ["Potsin", "Buduburam", "Nyanyano", "Fetteh", "Ojobi", "Dampase"] },
        "Gomoa West": { code: "CI", cities: ["Apam", "Mumford", "Dawurampong", "Dago", "Pinanko", "Kyiren Nkwanta"] },
        "Hemang Lower Denkyira": { code: "CH", cities: ["Twifo Hemang", "Jukwa", "Wawase", "Mampong"] },
        "Komenda Edina Eguafo": { code: "CK", cities: ["Elmina", "Komenda", "Agona Abrem", "Kissi", "Dominase", "Bantama"] },
        "Mfantseman": { code: "CM", cities: ["Saltpond", "Mankessim", "Anomabo", "Biriwa", "Yamoransa", "Kormantse", "Abeadze Dominase"] },
        "Twifo Ati-Morkwa": { code: "CT", cities: ["Twifo Praso", "Morkwa", "Wamaso", "Twifo Agona"] },
        "Upper Denkyira East": { code: "CU", cities: ["Dunkwa-on-Offin", "Kyekyewere", "Buabinso", "Meretweso"] },
        "Upper Denkyira West": { code: "CV", cities: ["Diaso", "Ayanfuri", "Dominase", "Ntom", "New Obuasi"] }
    },
    "Eastern Region": {
        "Abuakwa North": { code: "E4", cities: ["Kukurantumi", "Tafo", "Osiem", "Anyinasin"] },
        "Abuakwa South": { code: "E5", cities: ["Kyebi", "Bunso", "Apedwa", "Asiakwa", "Kibi"] },
        "Achiase": { code: "EC", cities: ["Achiase", "Akenkansu", "Aperade"] },
        "Akuapem North": { code: "E2", cities: ["Akropong", "Aburi", "Larteh", "Mamfe", "Mampong", "Amanokrom", "Tutunampong"] },
        "Akuapem South": { code: "E3", cities: ["Aburi", "Nsawam", "Pakro", "Kitase", "Berekuso"] },
        "Akyemansa": { code: "EM", cities: ["Ofoase", "Ayirebi", "Abenase", "Brenase"] },
        "Asene Manso Akroso": { code: "E8", cities: ["Akim Manso", "Akim Akroso", "Asene"] },
        "Asuogyaman": { code: "EA", cities: ["Atimpoku", "Akosombo", "Juapong", "Frankadua", "Labolabo", "Gyakiti"] },
        "Atiwa East": { code: "E9", cities: ["Anyinam", "Sekyere", "Mampong", "Enyiresi"] },
        "Atiwa West": { code: "ET", cities: ["Kwabeng", "Abomosu", "Akyem Akropong"] },
        "Ayensuano": { code: "EO", cities: ["Coaltar", "Teacher Mante", "Amanase", "Asuboi", "Anum Apapam"] },
        "Birim Central": { code: "EB", cities: ["Akim Oda", "Nkwanta", "Aboabo"] },
        "Birim North": { code: "EX", cities: ["New Abirem", "Afosu", "Akoase", "Ntronang", "Pankese"] },
        "Birim South": { code: "EZ", cities: ["Akim Swedru", "Aperade", "Achiasi"] },
        "Denkyembour": { code: "ED", cities: ["Akwatia", "Topremang", "Boadua", "Okumaning"] },
        "Fanteakwa North": { code: "EF", cities: ["Begoro", "Abourso", "Ahomahomasu", "Asirebuso", "Dedeso", "Dedeso (Dedesowirako)", "Obooho", "Feyiase", "Miaso", "Papramantang", "Otuater", "Ayensu"] },
        "Fanteakwa South": { code: "E6", cities: ["Osino", "Ehiamankyene", "Ehiamankyene (Ehiamankyene-Odumase)", "Bosuso", "Nsutam", "Dwenase", "Abompe", "Adjeikrom", "Akyem Hemang", "Saaman", "Summer"] },
        "Kwaebibirem": { code: "EK", cities: ["Kade", "Asuom", "Akwatia", "Wenchi", "Otumi", "Abodom"] },
        "Kwahu Afram Plains North": { code: "EP", cities: ["Donkorkrom", "Amankwakrom", "Bruben"] },
        "Kwahu Afram Plains South": { code: "EQ", cities: ["Tease", "Ekye Amanfrom", "Forifori"] },
        "Kwahu East": { code: "EH", cities: ["Abetifi", "Pepease", "Nkwatia", "Hweehwee", "Bokuruwa", "Ankoma", "Tafo", "Nteso", "Abene", "Abene", "Oworobong", "Sempoa"] },
        "Kwahu South": { code: "EI", cities: ["Mpraeso", "Obomeng", "Obo", "Atibie", "Bepong", "Aduamoa", "Asakraka", "Akwaseho", "Kwahu-Tafo", "Kotoso", "Osubeng"] },
        "Kwahu West": { code: "EJ", cities: ["Nkawkaw", "Jejeti", "Asona", "Apesika", "Asuboni No. 3", "Asuboni Rail", "Atibie Amanfrom", "Ekowso", "Fodoa", "Kwahudaa", "Kwahu Nsaba", "Mpraeso Amanfrom", "Nkwanda No. 1", "Nkwanda No. 2", "Obomeng Odumase", "Oframase", "Wisiwisi"] },
        "Lower Manya Krobo": { code: "EL", cities: ["Odumase-Krobo", "Agormanya", "Kpong", "Akuse", "Nuaso"] },
        "New Juaben North": { code: "E7", cities: ["Effiduase", "Asokore", "Oyoko", "Jumapo", "Suhyen"] },
        "New Juaben South": { code: "EN", cities: ["Koforidua", "Adweso", "Zongo"] },
        "Nsawam Adoagyiri": { code: "EG", cities: ["Nsawam", "Adoagyiri", "Dobro", "Nsumia"] },
        "Okere": { code: "ER", cities: ["Adukrom", "Apirede", "Abiriw", "Dawu", "Awukugua"] },
        "Suhum": { code: "ES", cities: ["Suhum", "Nankese", "Akorabo", "Okorase", "Brong Densuso", "Obretema", "Omenako", "Adarkwa", "Okanta", "Abenabo No. 2", "Kofigya", "Ayisaa", "Akote", "Aponoapono", "Amanhia", "Supresu", "Otwe", "Densuso", "Kukua", "Odikro Akwei"] },
        "Upper Manya Krobo": { code: "EU", cities: ["Asesewa", "Sekesua", "Anyaboni"] },
        "Upper West Akim": { code: "EV", cities: ["Adeiso", "Mepom", "Asuokaw"] },
        "West Akim": { code: "EW", cities: ["Asamankese", "Osenase", "Brekumanso", "Sukrong"] },
        "Yilo Krobo": { code: "EY", cities: ["Somanya", "Nkurakan", "Oterkpolu", "Obawale"] }
    },
    "Greater Accra Region": {
        "Ablekuma Central": { code: "G7", cities: ["Abossey Okai", "Mataheko"] },
        "Ablekuma North": { code: "GF", cities: ["Odorkor", "Darkuman", "Kwashieman"] },
        "Ablekuma West": { code: "GU", cities: ["Dansoman", "Glefe"] },
        "Accra": { code: "GA", cities: ["Accra", "Ashiedu Keteke", "Osu Klottey", "Ablekuma South"] },
        "Ada East": { code: "GY", cities: ["Ada Foah", "Big Ada"] },
        "Ada West": { code: "GX", cities: ["Sege", "Koluedor", "Anyamam"] },
        "Adentan": { code: "GD", cities: ["Adenta", "Frafraha", "Adjiringanor"] },
        "Ashaiman": { code: "GB", cities: ["Ashaiman", "Lebanon", "Jericho"] },
        "Ayawaso Central": { code: "G2", cities: ["Kokomlemle", "Kotobabi", "New Town"] },
        "Ayawaso East": { code: "GV", cities: ["Nima", "Kanda"] },
        "Ayawaso North": { code: "G3", cities: ["Maamobi"] },
        "Ayawaso West": { code: "G4", cities: ["Dzorwulu", "Legon", "East Legon", "Roman Ridge"] },
        "Ga Central": { code: "GC", cities: ["Sowutuom", "Santa Maria", "Anyaa"] },
        "Ga East": { code: "GE", cities: ["Abokobi", "Dome", "Kwabenya", "Taifa"] },
        "Ga North": { code: "GG", cities: ["Ofankor", "Pokuase", "Amamorley"] },
        "Ga South": { code: "GS", cities: ["Ngleshie Amanfro", "Tuba", "Kokrobite"] },
        "Ga West": { code: "GW", cities: ["Amasaman", "Pokuase", "Medie", "Kotoku"] },
        "Korle Klottey": { code: "GR", cities: ["Osu", "Ridge", "Adabraka"] },
        "Kpone Katamanso": { code: "GK", cities: ["Kpone", "Katamanso", "Oyibi"] },
        "Krowor": { code: "G6", cities: ["Nungua"] },
        "La Dade Kotopon": { code: "GL", cities: ["La", "Labone", "Cantonments", "Burma Camp"] },
        "La Nkwantanang Madina": { code: "GM", cities: ["Madina", "Oyarifa", "Teiman"] },
        "Ledzokuku": { code: "GZ", cities: ["Teshie"] },
        "Ningo Prampram": { code: "GN", cities: ["Prampram", "Old Ningo", "Dawhenya", "Afienya"] },
        "Okaikwei North": { code: "GI", cities: ["Achimota", "Tesano", "Abeka"] },
        "Shai-Osudoku": { code: "GO", cities: ["Dodowa", "Asutsuare", "Ayikuma"] },
        "Tema": { code: "GT", cities: ["Tema Community 1-12", "Tema Manhean", "Sakumono"] },
        "Tema West": { code: "GQ", cities: ["Sakumono", "Lashibi", "Klagon"] },
        "Weija Gbawe": { code: "GJ", cities: ["Weija", "Gbawe", "Mallam", "McCarthy Hill"] }
    },
    "North East Region": {
        "Bunkpurugu Nakpanduri": { code: "MP", cities: ["Bunkpurugu", "Nakpanduri", "Bimbagu"] },
        "Chereponi": { code: "MC", cities: ["Chereponi", "Wenchiki", "Tombo", "Wonjuga"] },
        "East Mamprusi": { code: "ME", cities: ["Nalerigu", "Gambaga", "Langbinsi", "Sakogu"] },
        "Mamprugu Moaduri": { code: "MM", cities: ["Yagaba", "Kubori", "Loagri", "Yizesi"] },
        "West Mamprusi": { code: "MW", cities: ["Walewale", "Wulugu", "Janga", "Kparigu"] },
        "Yunyoo Nasuan": { code: "MY", cities: ["Yunyoo", "Nasuan", "Jimbale"] }
    },
    "Northern Region": {
        "Gushiegu": { code: "NG", cities: ["Gushiegu", "Kpatinga", "Nabuli", "Galwei"] },
        "Karaga": { code: "NR", cities: ["Karaga", "Pishigu", "Namburugu", "Sakulo"] },
        "Kpandai": { code: "NA", cities: ["Kpandai", "Katiejeli", "Ekumdi", "Balai", "Lonto"] },
        "Kumbungu": { code: "NK", cities: ["Kumbungu", "Dalun", "Bontanga", "Zangbalun", "Gupanarigu"] },
        "Mion": { code: "NI", cities: ["Sang", "Sambu", "Jimle", "Kpabia"] },
        "Nanumba North": { code: "NN", cities: ["Bimbilla", "Chamba", "Dakpaa", "Juua"] },
        "Nanumba South": { code: "NO", cities: ["Wulensi", "Lungni", "Pudua", "Nakpa"] },
        "Nanton": { code: "NU", cities: ["Nanton", "Tampion", "Zoggu", "Jan-Joree"] },
        "Saboba": { code: "NX", cities: ["Saboba", "Wapuli", "Demong", "Kuchawe"] },
        "Sagnerigu": { code: "NS", cities: ["Sagnerigu", "Education Ridge", "Kanvili", "Shishegu", "Katariga"] },
        "Savelugu": { code: "NV", cities: ["Savelugu", "Diare", "Pong-Tamale", "Moglaa"] },
        "Tamale": { code: "NT", cities: ["Tamale", "Kukuo", "Vitin", "Banvim", "Zogbeli", "Lamashegu", "Gumbihini"] },
        "Tatale Sangule": { code: "NF", cities: ["Tatale", "Sangule", "Kandin", "Sheini"] },
        "Tolon": { code: "NL", cities: ["Tolon", "Nyankpala", "Yapei", "Tali"] },
        "Yendi": { code: "NY", cities: ["Yendi", "Gnani", "Adibo", "Bunbon"] },
        "Zabzugu": { code: "NZ", cities: ["Zabzugu", "Nakpali", "Kuyuli", "Natom"] }
    },
    "Oti Region": {
        "Biakoye": { code: "OB", cities: ["Nkonya Ahenkro", "Worawora", "Kwamekrom", "Tapa Abotoase", "Nkonya Wuropong"] },
        "Guan": { code: "OG", cities: ["Likpe Mate", "Lolobi", "Santrokofi", "Akpafu", "Likpe Bakwa"] },
        "Jasikan": { code: "OJ", cities: ["Jasikan", "Bodada", "Okadjakrom", "Baglo", "Teteman"] },
        "Kadjebi": { code: "OK", cities: ["Kadjebi", "Asato", "Ahamansu", "Dodi Papase", "Poase Cement"] },
        "Krachi East": { code: "OE", cities: ["Dambai", "Asukawkaw", "Tokuroano", "Dormabin", "Pai-Katanga", "Kparekpare"] },
        "Krachi Nchumuru": { code: "OQ", cities: ["Chinderi", "Banda", "Borae No. 2", "Zongo Macheri"] },
        "Krachi West": { code: "OW", cities: ["Kete-Krachi", "Osramanae", "Borae", "Ntewusae"] },
        "Nkwanta North": { code: "ON", cities: ["Kpassa", "Damanko", "Sibi", "Tinjase"] },
        "Nkwanta South": { code: "OS", cities: ["Nkwanta", "Brewaniase", "Bonakye", "Kue"] }
    },
    "Savannah Region": {
        "Bole": { code: "SB", cities: ["Bole", "Bamboi", "Maluwe", "Mandari", "Tinga"] },
        "Central Gonja": { code: "SG", cities: ["Buipe", "Yapei", "Mpaha", "Kusawgu", "Sankpala"] },
        "East Gonja": { code: "SE", cities: ["Salaga", "Kpembe", "Mankango", "Kpalbe", "Abromase"] },
        "North East Gonja": { code: "SJ", cities: ["Kpalbe", "Bunjai", "Tuluwe"] },
        "North Gonja": { code: "SN", cities: ["Daboya", "Lingbinsi", "Mankarigu", "Tidrope"] },
        "Sawla Tuna Kalba": { code: "SS", cities: ["Sawla", "Tuna", "Kalba", "Gindabuo", "Nahari"] },
        "West Gonja": { code: "SW", cities: ["Damongo", "Larabanga", "Busunu", "Mognori"] }
    },
    "Upper East Region": {
        "Bawku": { code: "UA", cities: ["Bawku", "Mognori", "Kuka", "Gentiga", "Zuuku", "Bado", "Baribari"] },
        "Bawku West": { code: "UW", cities: ["Zebilla", "Binaba", "Tilli", "Soogo", "Sapeliga"] },
        "Binduri": { code: "UU", cities: ["Binduri", "Bazua", "Aniisi", "Zawse"] },
        "Bolgatanga": { code: "UB", cities: ["Bolgatanga", "Sumbrungu", "Sherigu", "Yorogo", "Zaare", "Bukere", "Soe"] },
        "Bolgatanga East": { code: "UE", cities: ["Zuarungu", "Kumbosco", "Gambibigo", "Dachio"] },
        "Bongo": { code: "UO", cities: ["Bongo", "Gowrie", "Zuarungu", "Soe", "Namoo"] },
        "Builsa North": { code: "UR", cities: ["Sandema", "Wiaga", "Chuchuliga", "Kadema"] },
        "Builsa South": { code: "US", cities: ["Fumbisi", "Gbedema", "Doninga", "Wiesi"] },
        "Garu": { code: "UG", cities: ["Garu", "Denugu", "Songo", "Worikambo"] },
        "Kassena Nankana East": { code: "UK", cities: ["Navrongo", "Pungu", "Doba", "Gia", "Kologo"] },
        "Kassena Nankana West": { code: "UL", cities: ["Paga", "Chiana", "Mirigu", "Sirigu", "Kandiga", "Kajelo"] },
        "Nabdam": { code: "UN", cities: ["Nangodi", "Pelungu", "Sakote", "Zanlerigu"] },
        "Pusiga": { code: "UP", cities: ["Pusiga", "Kulungugu", "Widana", "Pulmakom"] },
        "Talensi": { code: "UT", cities: ["Tongo", "Datuku", "Pwalugu", "Winkogo", "Sheaga"] },
        "Tempane": { code: "UM", cities: ["Tempane", "Woriyanga", "Basyonde", "Bugri"] }
    },
    "Upper West Region": {
        "Daffiama Bussie Issa": { code: "XD", cities: ["Issa", "Daffiama", "Bussie", "Kojokperi", "Fian"] },
        "Jirapa": { code: "XJ", cities: ["Jirapa", "Hain", "Tizza", "Ullo", "Sabuli", "Duori", "Gbare"] },
        "Lambussie Karni": { code: "XK", cities: ["Lambussie", "Hamile", "Karni", "Samoa", "Bangwon"] },
        "Lawra": { code: "XL", cities: ["Lawra", "Babile", "Eremon", "Zambo"] },
        "Nadowli Kaleo": { code: "XO", cities: ["Nadowli", "Kaleo", "Takpo", "Juo", "Sankana"] },
        "Nandom": { code: "XN", cities: ["Nandom", "Ko", "Tuopare", "Puffien"] },
        "Sissala East": { code: "XS", cities: ["Tumu", "Wallenbelle", "Bugubelle", "Korgu"] },
        "Sissala West": { code: "XT", cities: ["Gwollu", "Jeffisi", "Zini", "Fielmua"] },
        "Wa": { code: "XW", cities: ["Wa", "Bamahu", "Kperisi", "Nayiri", "Charingu", "Busa"] },
        "Wa East": { code: "XX", cities: ["Funsi", "Bulenga", "Kundungu", "Loggu"] },
        "Wa West": { code: "XY", cities: ["Wechiau", "Dorimon", "Varempere"] }
    },
    "Volta Region": {
        "Adaklu": { code: "VA", cities: ["Adaklu Waya", "Adaklu Abuadi", "Adaklu Have", "Adaklu Tsrefe"] },
        "Afadjato South": { code: "VF", cities: ["Ve Golokuati", "Liati Wote", "Liati Soba", "Ve Deme", "Gbledi"] },
        "Agotime Ziope": { code: "VG", cities: ["Kpetoe", "Ziope", "Agotime Koforidua", "Bokor"] },
        "Akatsi North": { code: "VW", cities: ["Ave Dakpa", "Ave Afiadenyigba", "Have-Etoe", "Wute"] },
        "Akatsi South": { code: "VX", cities: ["Akatsi", "Avenorpedo", "Dagbamate", "Xavi", "Dzalele"] },
        "Anloga": { code: "VN", cities: ["Anloga", "Tegbi", "Woe", "Kome", "Srogboe", "Whuti", "Alakple"] },
        "Central Tongu": { code: "VV", cities: ["Adidome", "Mafi Kumase", "Mafi Adidome", "New Adidome", "Deveme"] },
        "Ho": { code: "VH", cities: ["Ho", "Sokode", "Dome", "Bankoe", "Tanyigbe", "Matse"] },
        "Ho West": { code: "VI", cities: ["Dzolokpuita", "Tsito", "Anyirawase", "Volo", "Kpedze"] },
        "Hohoe": { code: "VC", cities: ["Hohoe", "Fodome", "Golokwati", "Wli", "Alavanyo", "Gbi-Wegbe", "Abansi"] },
        "Keta": { code: "VK", cities: ["Keta", "Dzelukope", "Abor", "Anyanui", "Hatorgodo", "Vui", "Kedzi"] },
        "Ketu North": { code: "VY", cities: ["Dzodze", "Penyi", "Afife", "Hevi", "Ehi", "Dekpor"] },
        "Ketu South": { code: "VZ", cities: ["Denu", "Aflao", "Agbozume", "Klikor", "Somey", "Akame"] },
        "Kpando": {
            code: "VP", cities: ["Kpando", "Kpando Gabi", "Kpando Tsape", "Kpando Aloyi",
                "Kpando Agbenoxoe", "Kpando Agudzi", "Kpando Aziave", "Kpando Bame", "Kpando Dafor",
                "Kpando Dzewoe", "Kpando Dzigbe", "Kpando Dzoanti", "Kpando Fesi", "Kpando Gadza", "Kpando Konda",
                "Avetikofe", "Tokor", "Gbefi Hoeme", "Gbefi Tonu", "Sovie", "Kudzra", "Dafor"
            ]
        },
        "North Dayi": { code: "VD", cities: ["Anfoega", "Vakpo", "Kusorganu", "Anfoega Akukome", "Awate"] },
        "North Tongu": { code: "VT", cities: ["Battor", "Mepe", "Juapong", "Aveyime", "Dugame"] },
        "South Dayi": { code: "VE", cities: ["Kpeve", "Peki", "Dzemeni", "Tornu", "Sadam"] },
        "South Tongu": { code: "VU", cities: ["Sogakope", "Dabala", "Agave", "Tefle", "Adutor", "Kpotame"] }
    },
    "Western Region": {
        "Ahanta West": { code: "WH", cities: ["Agona Nkwanta", "Dixcove", "Busua", "Abura", "Apowa", "Butre", "Akimim"] },
        "Effia Kwesimintim": { code: "WK", cities: ["Effia", "Kwesimintsim", "Effia Kuma", "Anaji", "Assakae", "Apremdo"] },
        "Ellembelle": { code: "WE", cities: ["Nkroful", "Esiama", "Aiyinasi", "Atuabo", "Kikam", "Kamgbunli"] },
        "Jomoro": { code: "WJ", cities: ["Half Assini", "Elubo", "Beyin", "Tikobo No. 1", "Tikobo No. 2", "Sowodadzem"] },
        "Mpohor": { code: "WM", cities: ["Mpohor", "Adum Banso", "Mansoman", "Ayiem"] },
        "Nzema East": { code: "WN", cities: ["Axim", "Bamiankor", "Kutukrom", "Amanfukuman"] },
        "Prestea Huni Valley": { code: "WP", cities: ["Prestea", "Bogoso", "Huni Valley", "Aboso", "Bepo", "Damang"] },
        "Sekondi-Takoradi": { code: "WS", cities: ["Sekondi", "Takoradi", "Kojokrom", "Essikado", "Ketan", "Adiembra", "Fijai", "Effiakuma"] },
        "Shama": { code: "WR", cities: ["Shama", "Abuesi", "Shama Junction", "Aboadze", "Ituma", "Inchaban"] },
        "Tarkwa Nsuaem": { code: "WT", cities: ["Tarkwa", "Nsuaem", "Aboso", "Bonsaso", "Dompim", "Benso"] },
        "Wassa Amenfi Central": { code: "WW", cities: ["Manso Amenfi", "Adjakaa Manso", "Agona Amenfi", "Bonuama"] },
        "Wassa Amenfi East": { code: "WX", cities: ["Wassa Akropong", "Japa", "Nananko", "Adameobuo"] },
        "Wassa Amenfi West": { code: "WY", cities: ["Asankragua", "Samreboi", "Asanwinso", "Mumuaduo"] },
        "Wassa East": { code: "WZ", cities: ["Daboase", "Ateiku", "Enyinabrim", "Sekyere Krobo", "Senchem"] }
    },
    "Western North Region": {
        "Aowin": { code: "YA", cities: ["Enchi", "Omanpe", "Boinso", "Yakasi", "Jema"] },
        "Bia East": { code: "YE", cities: ["Adabokrom", "Kaase", "Asuopiri"] },
        "Bia West": { code: "YW", cities: ["Essam-Dabiso", "Oseikojokrom", "Adjoafua", "Akotuakrom"] },
        "Bibiani Anhwiaso Bekwai": { code: "YB", cities: ["Bibiani", "Sefwi Bekwai", "Anhwiaso", "Awaso", "Sefwi Wiawso"] },
        "Bodi": { code: "YD", cities: ["Bodi", "Amoaya", "Kwasikrom", "Afere"] },
        "Juaboso": { code: "YJ", cities: ["Juaboso", "Benchemaa", "Aboaboso", "Bonsu Nkwanta"] },
        "Sefwi Akontombra": { code: "YK", cities: ["Sefwi Akontombra", "Nkwadum", "Ackaakrom", "Nisoyame"] },
        "Sefwi Wiawso": { code: "YS", cities: ["Wiawso", "Dwinase", "Asawinso", "Sefwi Asawinso", "Datano"] },
        "Suaman": { code: "YU", cities: ["Dadieso", "Karla", "Suaman"] }
    }
};
